spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**
  application:
    name: api-gateway
server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}