#!/bin/sh

#cd ./service-registry
#./mvnw -DskipTests=true clean package

cd ./user-service
./mvnw -DskipTests=true clean package

cd ../post-service
./mvnw -DskipTests=true clean package

cd ..
docker-compose build
docker-compose up